DATASET:
  dataset : "OfficeHome"
  communication_epoch : 50
  n_classes: 65
  parti_num: 4
  online_ratio: 1.0
  domain_ratio: 0.1
  train_eval_domain_ratio: 1.0
  backbone: "resnet18" # resnet18_lora
  pretrained: False
  aug: "two_weak"

OPTIMIZER:
  type: 'SGD'
  momentum: 0.9
  weight_decay: 1e-5
  local_epoch: 10 # 10
  local_train_batch: 64
  local_test_batch: 64
  local_train_lr: 1e-2 # 0.01


