
DATASET:
  dataset : "PACScomb"
  communication_epoch : 50
  n_classes: 7
  parti_num: 3
  online_ratio: 1.0
  domain_ratio: 1.0
  train_eval_domain_ratio: 1.0
  backbone: "resnet18"
  pretrained: False
  use_two_crop: False
  rank: 4
  lora_alpha: 1
  lora_dropout: 0
  ood_ratio: 1


OPTIMIZER:
  type: 'SGD'
  momentum: 0.9
  weight_decay: 1e-5
  local_epoch: 1 # 10
  local_train_batch: 32
  local_test_batch: 32
  local_train_lr: 1e-2 # 0.01


