
DATASET:
  dataset : "DomainNet"
  communication_epoch : 50
  n_classes: 345
  parti_num: 4
  online_ratio: 1.0
  domain_ratio: 1.0e-3
  train_eval_domain_ratio: 1.0e-3
  backbone: "resnet18_pretrained" # resnet18_lora
  pretrained: True
  aug: "two_weak"

OPTIMIZER:
  type: 'SGD'
  momentum: 0.9
  weight_decay: 1e-5
  local_epoch: 1 # 10
  local_train_batch: 64
  local_test_batch: 64
  local_train_lr: 1e-2 # 0.01


