DATASET:
  dataset : "fl_tinyimagenet"
  communication_epoch : 100
  n_classes: 200
  parti_num: 10
  aug: "weak"
  beta: 0.5
  backbone: "resnet50"

OPTIMIZER:
  type: 'SGD'
  momentum: 0.9
  weight_decay: 1e-5
  local_epoch: 10
  local_train_batch: 64
  local_test_batch: 64
  val_batch: 64
  local_train_lr: 1e-2
