DATASET:
  dataset : "Digits"
  communication_epoch : 50
  n_classes: 10
  parti_num: 5 #
  online_ratio: 1.0
  domain_ratio: 0.5 # 扩大了到1.0
  train_eval_domain_ratio: 0.1
  backbone: "simple_cnn" # simple_cnn resnet18_pretrained resnet18
  pretrained: False # True False
  aug: "weak"

OPTIMIZER:
  type: 'SGD'
  momentum: 0.9
  weight_decay: 1e-5
  local_epoch: 1 # 10
  local_train_batch: 64
  local_test_batch: 64
  val_batch: 64
  local_train_lr: 1e-2 # 0.01
